<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static create(array $array)
 * @method static find($id)
 */
class TargetReconnaissance extends Model
{
    use HasFactory;
    protected $table = 'target_reconnaissances';
    protected $fillable = ['task_id', 'position_id', 'position_type_id', 'user_id', 'status', 'description', 'documents'];
    protected $hidden = ['created_at', 'updated_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function($targetReconnaissance){
            $targetReconnaissance->position()->delete();
            $user_task = UserTask::where('task_id', $targetReconnaissance->task_id)->where('user_id', $targetReconnaissance->user_id)->first();
            if($user_task){
                $user_task->delete();
            }
        });
    }

    public function position(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Position::class, 'id', 'position_id');
    }

    public function locationCategory(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(PositionType::class, 'id', 'position_type_id');
    }

    public function user(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}
